# Generated by Django 5.2 on 2025-09-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_baseuser_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'الدور', 'verbose_name_plural': 'الادوار'},
        ),
        migrations.AddField(
            model_name='client',
            name='location',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
