# Generated by Django 5.2 on 2025-09-05 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_role_options_client_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'verbose_name': 'عنصر', 'verbose_name_plural': 'عناصر'},
        ),
        migrations.AddField(
            model_name='baseuser',
            name='role',
            field=models.CharField(blank=True, choices=[('manager', 'Manager'), ('accountant', 'Accountant'), ('salesman', 'Salesman')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='first_name',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='last_name',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.client'),
        ),
    ]
